launcher_args: {experiment_name: marason_inten_nist20,
  script_name: "src/ms_pred/marason/train_inten.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local,
  visible_devices: [0],
  max_parallel_per_gpu: 1
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G,
   nodelist: 'node[1236]', time: '1-18:00:00'}
  debug: [false]
  debug-overfit: [false]
  gpu: [true]
 
  seed: [1]
  num-workers: [32]
  batch-size: [32]
  max-epochs: [200]

  dataset-name: [nist20]
  split-name: [split_1.tsv]

  include-unshifted-mz: [false]
  multi-gnn: [true]
  learning-rate: [0.0004]
  lr-decay-rate: [0.825]
  sk-tau: [0.05]
  softmax-tau: [0.02]
  dropout: [0.1]
  mpnn-type: [GGNN]
  pe-embed-k: [0]
  pool-op: [avg]
  hidden-size: [256]
  weight-decay: [1e-7]
  set-layers: [0]
  frag-set-layers: [3]
  inten-layers: [2]
  mlp-layers: [1]
  gnn-layers: [4]
  loss-fn: [cosine]
  root-encode: [gnn]
  inject-early: [false]
  binned-targs: [true] 
  embed-adduct: [true]
  embed-collision: [true]
  embed-elem-group: [true]
  grad-accumulate: [1]
  encode-forms: [true]
  add-hs: [true]
  add-reference: [false]
  load-reference: [false]
  save-reference: [false]
  reference-dir: ["data/closest_neighbors/infinite"]
  max-ref-count: [3]
  filter: [false]
  filter-valid-test: [false]
  logger: ["marason_inten_train_unshift_mz_cos"]
  matching-method: ["softmax"]


iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd1]
     magma-dag-folder: [results/marason_nist20/split_1_rnd1/preds_train_100_inten.hdf5]
     seed: [1]

  # -  split-name: [split_1.tsv]
  #    save-dir: [split_1_rnd2]
  #    magma-dag-folder: [results/marason_nist20/split_1_rnd2/preds_train_100_inten.hdf5]
  #    seed: [2]

  # -  split-name: [split_1.tsv]
  #    save-dir: [split_1_rnd3]
  #    magma-dag-folder: [results/marason_nist20/split_1_rnd3/preds_train_100_inten.hdf5]
  #    seed: [3]

  # -  split-name: [scaffold_1.tsv]
  #    save-dir: [scaffold_1_rnd1]
  #    magma-dag-folder: [results/marason_nist20/scaffold_1/preds_train_100_inten.hdf5]
  #    seed: [1]
  #    reference-dir: ["data/closest_neighbors/infinite/scaffold"]

  # -  split-name: [scaffold_1.tsv]
  #    save-dir: [scaffold_1_rnd2]
  #    magma-dag-folder: [results/marason_nist20/scaffold_1/preds_train_100_inten.hdf5]
  #    seed: [2]
  #    reference-dir: ["data/closest_neighbors/infinite/scaffold"]

  # -  split-name: [scaffold_1.tsv]
  #    save-dir: [scaffold_1_rnd3]
  #    magma-dag-folder: [results/marason_nist20/scaffold_1/preds_train_100_inten.hdf5]
  #    seed: [3]
  #    reference-dir: ["data/closest_neighbors/infinite/scaffold"]
